# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# GHC 8.8.3
resolver: lts-16.8

packages:
  - '.'

extra-deps: []

flags: {}

allow-newer: false
